<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="item-qty-info">
            <div data-bind="scope: 'qty-counter'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <div class="stock-availability">
                <img alt="" src="<?= $this->getViewFileUrl('Magento_Catalog::images/check-mark.svg'); ?>"/>
                <p class="in-stock">In stock</p>
                <p class="amount-in-stock">
                    <?= $_product->getExtensionAttributes()->getStockItem()->getQty(); ?> items available
                </p>
            </div>
        </div>
        <div class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty-counter": {
                        "component": "Magento_Catalog/js/qty-counter",
                        "template": "Magento_Catalog/input-counter",
                        "qty": "<?= $block->getProductDefaultQty() * 1; ?>",
                        "dataValidate": "<?= $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"
                    }
                }
            }
        }
    }

</script>
