<?php

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <?php $shownAttributes = array_slice($_additional, 0, 3); ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <ul>
            <?php foreach ($shownAttributes as $_data) :?>
                <li>
                    <p class="attribute-label" ><?= $block->escapeHtml($_data['label']) ?>:
                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></p>
                </li>
            <?php endforeach; ?>
            </ul>
        </table>
    </div>
<?php endif;?>
